# Generated by Django 5.2.12 on 2026-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_details',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
